### ISSUE TITLE
Support ruby version 2.7.X 

### ISSUE THREAD

**Issue by marciojg** [karafka/karafka#1045]
The support for the ruby 2.7.X is not been applied as we have in the documentation of the gem. 

![Screenshot_20220928_205719](https://user-images.githubusercontent.com/14796991/192908857-1a1967dc-05d2-4586-9be6-62d0183622f9.png)

In the version `2.0.7` of the gem was implemented a [shorthand syntax](https://github.com/karafka/karafka/blob/v2.0.7/lib/karafka/routing/proxy.rb#L19) for arguments that only have support on ruby 3.0 + 

--------

## Expected behavior

Start karafka server with success when executing the command `bundle exec karafka server` with my ruby version 2.7.x

## Actual behavior

When the karafka version is `>= 2.0.7` and I execute the command  `bundle exec karafka server` this exception is raised:

```
bash-5.0# bundle exec karafka server
bundler: failed to load command: karafka (/usr/local/bundle/bin/karafka)
SyntaxError: /usr/local/bundle/gems/karafka-2.0.7/lib/karafka/routing/proxy.rb:19: syntax error, unexpected (...
...method_missing(method_name, ...)
...                            ^~~
/usr/local/bundle/gems/karafka-2.0.7/lib/karafka/routing/proxy.rb:23: syntax error, unexpected ')'
...c_send(:"#{method_name}=", ...)
...                              ^
/usr/local/bundle/gems/karafka-2.0.7/lib/karafka/routing/proxy.rb:25: syntax error, unexpected ')'
...t.public_send(method_name, ...)
...                              ^
/usr/local/bundle/gems/karafka-2.0.7/lib/karafka/routing/proxy.rb:39: syntax error, unexpected end-of-input, expecting `end'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
  /usr/local/bundle/gems/karafka-2.0.7/lib/active_job/karafka.rb:18:in `<top (required)>'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
  /usr/local/bundle/gems/karafka-2.0.7/lib/karafka/railtie.rb:24:in `<top (required)>'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:234:in `block in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `synchronize'
  /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `eager_load'
  /usr/local/bundle/gems/karafka-2.0.7/lib/karafka.rb:101:in `<top (required)>'
  /usr/local/bundle/gems/karafka-2.0.7/bin/karafka:3:in `require'
  /usr/local/bundle/gems/karafka-2.0.7/bin/karafka:3:in `<top (required)>'
  /usr/local/bundle/bin/karafka:25:in `load'
  /usr/local/bundle/bin/karafka:25:in `<top (required)>'
```

## Steps to reproduce the problem

- Use ruby version `2.7.X`
- Use karafka version `2.0.7`
- Execute `bundle exec karafka server` or `bundle exec karafka info`

## My setup details

```
$ [bundle exec] karafka info
Karafka version: 2.0.7
Ruby version: 2.7.1
Application client id: karafka-local
Backend: inline
Batch fetching: true
Batch consuming: true
Boot file: /app/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://kafka:9092"]
```

**Comment by mensfeld** [comment]
Hmmm why did the specs not catch it. Let me check.

**Comment by mensfeld** [comment]
Ok, I know. Works with 2.7.6 but does not work with 2.7.0.

**Comment by mensfeld** [comment]
It was backported to 2.7.3: https://bugs.ruby-lang.org/issues/16378
