### ISSUE TITLE
Karafka::Instrumentation::Vendors::Datadog::Listener#on_connection_listener_fetch_loop_received

### ISSUE THREAD

**Issue by vadim-handy** [karafka/karafka#1109]
### Summary

When running the StatsD/Datadog Listener locally, the method `on_connection_listener_fetch_loop_received` is given an event payload that does not contain `:subscription_group`, which is needed to collect metrics: 

```ruby 
event[:subscription_group]
=> eval error: key not found: :subscription_group
```

The available keys are: 

```ruby 
event.payload.keys
=> [:caller, :messages_buffer, :time]
```

The subscription group can be extracted with the following instead: 

```ruby 
event.payload[:messages_buffer].instance_variable_get(:@subscription_group).id
=> "df23aae5-2a36-4752-816d-d3fdb052bedf"

# OR 

event[:caller].instance_variable_get(:@subscription_group).id
"df23aae5-2a36-4752-816d-d3fdb052bedf"

# OR to match LoggerListener, using the Listener id instead

event[:caller].id
=>"80136b7a-9d45-4616-93f1-a784901c2125"
```

## Expected behavior

`Karafka::Instrumentation::Vendors::Datadog::Listener#on_connection_listener_fetch_loop_received` collects metrics `['listener.polling.time_taken', 'listener.polling.messages']` given a `Karafka::Core::Monitoring::Event`

## Actual behavior

`Karafka::Instrumentation::Vendors::Datadog::Listener#on_connection_listener_fetch_loop_received` errors with: 

```ruby 
eval error: key not found: :subscription_group
  .../gems/dry-events-0.3.0/lib/dry/events/event.rb:54:in `fetch'
  .../gems/dry-events-0.3.0/lib/dry/events/event.rb:54:in `[]'
  .../example-apps/v2.0-rails/karafka.rb:1:in `on_connection_listener_fetch_loop_received'
```

## Steps to reproduce the problem

1. Open the [example apps repo](https://github.com/karafka/example-apps)
2. Add a debugger to help diagnose the issue
```ruby 
# Gemfile
group :development, :test do
  gem 'karafka-testing', '>= 2.0.0.alpha3'
  gem 'rspec'
  gem "debug", '>= 1.0.0' # Added
end
```
3. Edit `v2.0-rails/karafka.rb` to require `karafka/instrumentation/vendors/datadog/listener`, and mock a `StatsdDummyClient` to receive metrics. 
```ruby 
# frozen_string_literal: true

require ::File.expand_path('config/environment', __dir__)

# MODIFIED - INCLUDE datadog/listener
require 'karafka/instrumentation/vendors/datadog/listener'

# MODIFIED - CREATE StatsdDummyClient to collect metrics
class StatsdDummyClient
  attr_reader :buffer

  def initialize
    @buffer = Hash.new do |buffer, dd_method|
      buffer[dd_method] = Hash.new do |key_scope, metric|
        key_scope[metric] = []
      end
    end
  end

  %i[
    count
    histogram
    gauge
    increment
    decrement
  ].each do |method_name|
    define_method method_name do |metric, value = nil, details = {}|
      @buffer[method_name][metric] << [value, details]
    end
  end
end

# Karafka app object
class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka = { "bootstrap.servers": '127.0.0.1:9092' }
    config.client_id = 'example_app'
    config.concurrency = 2
    config.max_wait_time = 5000 # 0.5 second
    # Recreate consumers with each batch. This will allow Rails code reload to work in the
    # development mode. Otherwise Karafka process would not be aware of code changes
    config.consumer_persistence = !Rails.env.development?
  end

# MODIFIED - CREATE Datadog::Listener with the dummy client
  dd_listener = ::Karafka::Instrumentation::Vendors::Datadog::Listener.new do |config|
    config.client = StatsdDummyClient.new
    # Publish host as a tag alongside the rest of tags
    config.default_tags = ["host:#{Socket.gethostname}"]
  end

# MODIFIED - REDEFINE #on_connection_listener_fetch_loop_received to throw you in a debugger when hit
  def dd_listener.on_connection_listener_fetch_loop_received(event)
    debugger

    time_taken = event[:time]
    messages_count = event[:messages_buffer].size
    consumer_group_id = event[:subscription_group].consumer_group_id

    histogram('listener.polling.time_taken', time_taken, tags: ["consumer_group:#{consumer_group_id}"])
    histogram('listener.polling.messages', messages_count, tags: ["consumer_group:#{consumer_group_id}"])
  end

# MODIFIED - SUBSCRIBE
  Karafka.monitor.subscribe(dd_listener)

  routes.draw do
    # This needs to match queues defined in your ActiveJobs
    active_job_topic :default

    topic :visits do
      consumer VisitsConsumer
    end
  end
end
```
4. Start up a karafka server and wait for it to start polling to hit your debugger
```
❯ bundle exec karafka server
[49, 58] in ~/Documents/example-apps/v2.0-rails/karafka.rb
```
5. Interact with the event instance to confirm that it does not have the required key. 
```ruby 
time_taken = event[:time]
=> 5423
messages_count = event[:messages_buffer].size
=> 0
consumer_group_id = event[:subscription_group].consumer_group_id
=> eval error: key not found: :subscription_group
  /Users/vfainberg/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/karafka-core-2.0.3/lib/karafka/core/monitoring/event.rb:21:in `fetch'
  /Users/vfainberg/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/karafka-core-2.0.3/lib/karafka/core/monitoring/event.rb:21:in `[]'
  (rdbg)//Users/vfainberg/Documents/example-apps/v2.0-rails/karafka.rb:1:in `on_connection_listener_fetch_loop_received'
```

## Your setup details

Reproduced with both the Karafka version in the example-app repo as well as the upgraded 2.0.15

Reproducible on Karafa 2.0.0.rc3.:

```
Karafka version: 2.0.0.rc3
Ruby version: 3.1.2
Rdkafka version: 0.12.0
Subscription groups count: 1
Workers count: 2
Application client id: example_app
Boot file:  ~/Documents/example-apps/v2.0-rails/karafka.rb
Environment: development
License: LGPL-3.0
```

Reproducible on Karafa 2.0.15:
```
Karafka version: 2.0.15
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]
Rdkafka version: 0.12.0
Subscription groups count: 1
Workers count: 2
Application client id: example_app
Boot file: ~/Documents/example-apps/v2.0-rails/karafka.rb
Environment: development
License: LGPL-3.0
```

rfkafka version from Gemfile.lock
```
rdkafka (0.12.0)
```

**Comment by mensfeld** [comment]
@vadim-handy

> When running the StatsD/Datadog Listener locally, the method on_connection_listener_fetch_loop_received is given an event payload that does not contain :subscription_group, which is needed to collect metrics

I look here: https://github.com/karafka/karafka/blob/master/lib/karafka/instrumentation/vendors/datadog/listener.rb#L106

and there is a `:subscription_group` present.

It is not yet released but will go with the upcoming one. Ref https://github.com/karafka/karafka/issues/1093
