### ISSUE TITLE
2.0.16 DeadLetterQueue feature seems to not be protected

### ISSUE THREAD

**Issue by tmtrademarked** [karafka/karafka#1144]
## Actual behavior

When starting a rails process, Karafka raises an error. I suspect the `Builder` class for the DLQ feature is not correctly declared somewhere for the autoloader to find it as expected:

```
/Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/karafka-2.0.16/lib/karafka/routing/features/base.rb:17:in `activate': uninitialized constant Karafka::Routing::Features::DeadLetterQueue::Builder (NameError)

            Proxy.prepend(self::Builder) if const_defined?('Builder')
                              ^^^^^^^^^
Did you mean?  Jbuilder

from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/karafka-2.0.16/lib/karafka/routing/features/base.rb:28:in `each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/karafka-2.0.16/lib/karafka/routing/features/base.rb:28:in `load_all'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/karafka-2.0.16/lib/karafka.rb:98:in `<main>'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `each'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:44:in `require'
	from /Users/tom.wilson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler.rb:187:in `require'
	from /Volumes/android/agora/config/application.rb:19:in `<main>'
```

## Steps to reproduce the problem

For me, this was as simple as:
* Update from Karafka 2.0.15 to 2.0.16
* Run rails c, rails s, or any rsepc test

## Your setup details

Ruby 3.1.2, Rails 7.0.4

```
$ [bundle exec] karafka info
Karafka version: 2.0.16
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
Rdkafka version: 0.12.0
Subscription groups count: 1
Workers count: 5
Application client id: agora
Boot file: /Volumes/android/agora/karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
Let me try to repro this...

**Comment by mensfeld** [comment]
@tmtrademarked any chance you have a custom redefined `const_defined?`? it looks like it uses a different scope to check for the builder

**Comment by mensfeld** [comment]
Ok I can replicate. It's the visibiltiy scope of class called `Builder`. Not related to DLQ but to the injection engine. Fix is on its way.

**Comment by mensfeld** [comment]
Fix: https://github.com/karafka/karafka/pull/1145

**Comment by mensfeld** [comment]
I should craft a release in around 30 minutes.

**Comment by tmtrademarked** [comment]
Awesome - thanks for the super quick investigation and fix here!
