### ISSUE TITLE
Getting Error while starting embeded Karafka (id=>"needs to be a string with a Kafka accepted format)

### ISSUE THREAD

**Issue by gwthm-in** [karafka/karafka#1368]
We have a use case to consume events from Kafka in Ruby ecosystem. We have written a small wrapper over karafka to consume. The wrapper does nothing other than define routes and configure. 

```ruby
require 'event_bus_client'
require 'event_bus_logs'
require 'event/sample_worker'

EventBusClient.configure do |cfg|
  cfg.client_id = "nkapsi_accounts_development"
  cfg.bootstrap_servers = "localhost:9092"
  cfg.group_id = :event_bus_client
  cfg.initial_offset = :latest
end

EventBusClient.subscribe("test-topic", SimpleConsumer)
EventBusClient.start
```

And I'm getting the following error, not sure which id needs to be configured. 
```ruby
/opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-core-2.0.12/lib/karafka/core/contractable/contract.rb:102:in `validate!': {:id=>"needs to be a string with a Kafka accepted format"} (Karafka::Errors::InvalidConfigurationError)
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-2.0.33/lib/karafka/contracts/base.rb:13:in `validate!'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-2.0.33/lib/karafka/routing/builder.rb:37:in `block in draw'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-2.0.33/lib/karafka/routing/builder.rb:35:in `each'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-2.0.33/lib/karafka/routing/builder.rb:35:in `draw'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-2.0.33/lib/karafka/routing/features/base/expander.rb:37:in `block (2 levels) in prepended_module'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-2.0.33/lib/karafka/routing/features/base/expander.rb:37:in `block (2 levels) in prepended_module'
	from /opt/homebrew/lib/ruby/gems/3.2.0/gems/karafka-2.0.33/lib/karafka/routing/features/base/expander.rb:37:in `block (2 levels) in prepended_module'
	from /Users/GowthamSai/Documents/repos/shopuptech/event-bus-client-rb/lib/event_bus_client.rb:69:in `start'
	from (irb):11:in `<main>'
	from bin/console:15:in `<main>'
```

Version Info: 
```
karafka (2.0.33)
```

Here is the config of karafka:
```ruby
irb(main):015:1* Karafka::App.setup do |cfg|
irb(main):016:1*   puts cfg.kafka
irb(main):017:0> end
{:bootstrap_servers=>["localhost:9092"], :group_id=>"event_bus_client", :initial_offset=>"latest", :"client.id"=>"karafka", :"statistics.interval.ms"=>5000, :"allow.auto.create.topics"=>"true", :"topic.metadata.refresh.interval.ms"=>5000}
```

**Comment by mensfeld** [comment]
You are using consumer mapper against the docs: https://karafka.io/docs/Consumer-mappers/

it is expected to return a string but you are returning a symbol.

**Comment by mensfeld** [comment]
@gwthm-in does it solve your issue?

**Comment by gwthm-in** [comment]
yes, but I think error message could be improved?

**Comment by mensfeld** [comment]
@gwthm-in feel free to suggest a better one and happy to update :)
