### ISSUE TITLE
Issue with Rdkafka::Config::ClientCreationError

### ISSUE THREAD

**Issue by davidsth** [karafka/karafka#1558]
I'm running karafka 2.1.9

--------

## Expected behavior

Expect the SSL settings to work with the ssl.certificate.pem config that I'm passing in.

## Actual behavior

It's throwing the following error:
```
[ERR] bundler: failed to load command: karafka (../vendor_bundle/ruby/3.1.0/bin/karafka)
[ERR] ../vendor_bundle/ruby/3.1.0/gems/karafka-rdkafka-0.13.3/lib/rdkafka/config.rb:265:in `native_kafka': ssl.certificate.pem failed: not in PEM format?: error:0480006C:PEM routines::no start line: Expecting: CERTIFICATE (Rdkafka::Config::ClientCreationError)
[ERR] from ../vendor_bundle/ruby/3.1.0/gems/karafka-rdkafka-0.13.3/lib/rdkafka/config.rb:161:in `consumer'
[ERR] from ../vendor_bundle/ruby/3.1.0/gems/karafka-2.1.9/lib/karafka/connection/client.rb:475:in `build_consumer'
[ERR] from ../vendor_bundle/ruby/3.1.0/gems/karafka-2.1.9/lib/karafka/connection/client.rb:51:in `initialize'
[ERR] from ../vendor_bundle/ruby/3.1.0/gems/karafka-2.1.9/lib/karafka/connection/listener.rb:29:in `new'
[ERR] from ../vendor_bundle/ruby/3.1.0/gems/karafka-2.1.9/lib/karafka/connection/listener.rb:29:in `initialize'
[ERR] from ../vendor_bundle/ruby/3.1.0/gems/karafka-2.1.9/lib/karafka/connection/listeners_batch.rb:24:in `new'
[ERR] from ../vendor_bundle/ruby/3.1.0/gems/karafka-2.1.9/lib/karafka/connection/listeners_batch.rb:24:in `block (2 levels) in initialize'
```

I'm pretty sure my certs are fine since when I had karafka 1.0 it was working fine. The ssl.certificate.pem is in string format that looks like:

-----BEGIN CERTIFICATE-----
....
----END CERTIFICATE-----

I've also verified the cert is valid.

## Steps to reproduce the problem

When you configure ssl like the following, you should be able to reproduce it:
```
    {
      'bootstrap.servers': sanitize_kafka_host(ENV.fetch('KAFKA_HOST', 'nil')),
      'security.protocol': ENV.fetch('KAFKA_SECURITY_PROTOCOL', 'ssl'),
      'ssl.endpoint.identification.algorithm': ENV.fetch('KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM', 'https'),
      'ssl.certificate.pem': ENV.fetch('KAFKA_CLIENT_CERT', nil),
      'ssl.key.pem': ENV.fetch('KAFKA_CLIENT_CERT_KEY', nil),
      'ssl.key.password': ENV.fetch('KAFKA_CLIENT_CERT_KEY_PASSWORD', nil),
      'ssl.ca.location': ENV.fetch('SSL_CERT_FILE', nil)
    }
```

## Your setup details

Here's an example:

```
 $ bundle exec karafka info

Karafka version: 2.1.9
Ruby version: ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]
Rdkafka version: 0.13.3
Consumer groups count: 6
Subscription groups count: 6
Workers count: 5
Application client id: xxxx
Boot file: karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
@davidsth can you reproduce it with example app + docker? Otherwise I will blame it on your setup as all (seriously all) previous cases related to SSL and sasl.

**Comment by davidsth** [comment]
yes, had two environment variables, bad one replacing the other
