### ISSUE TITLE
Misleading error when non-existing dependency is required

### ISSUE THREAD

**Issue by filiptepper** [karafka/karafka#213]
I just stumbled into this scenario:

* very plain `karafka` application,
* in a controller I `require` a file that does not exist,
* I get `Karafka::Errors::MissingBootFile` exception, despite `karafka.rb` being present and `LoadError` existing in a different place.

Example application: https://github.com/filiptepper/karafka-boot-report

**Comment by mensfeld** [comment]
Damn. Simple solutions aren't always simple. Already started to work on manual commit but will fix that in a sec. Will just have to check for file existence instead of loading.

**Comment by filiptepper** [comment]
No rush, just reporting. Not a blocker on my end, but might be confusing.

**Comment by mensfeld** [comment]
@filiptepper absolutely true. Fix will be available in 15-20 minutes. Thank you.

**Comment by mensfeld** [comment]
this should do the job:
- try to require if available
- if not, then raise an exception unless it is a help or install command

**Comment by mensfeld** [comment]
Checked also against your repo:

```
/home/mencio/Pulpit/karafka-boot-report/app/controllers/application_controller.rb:3:in `require': cannot load such file -- raise-exception (LoadError)
	from /home/mencio/Pulpit/karafka-boot-report/app/controllers/application_controller.rb:3:in `<top (required)>'
	from /home/mencio/.rvm/gems/ruby-2.4.2/gems/require_all-1.4.0/lib/require_all.rb:108:in `require'
	from /home/mencio/.rvm/gems/ruby-2.4.2/gems/require_all-1.4.0/lib/require_all.rb:108:in `block in require_all'
	from /home/mencio/.rvm/gems/ruby-2.4.2/gems/require_all-1.4.0/lib/require_all.rb:106:in `each'
	from /home/mencio/.rvm/gems/ruby-2.4.2/gems/require_all-1.4.0/lib/require_all.rb:106:in `require_all'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bundler/gems/karafka-20e471cd078c/lib/karafka/loader.rb:26:in `load!'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bundler/gems/karafka-20e471cd078c/lib/karafka/loader.rb:19:in `block in load'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bundler/gems/karafka-20e471cd078c/lib/karafka/loader.rb:16:in `each'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bundler/gems/karafka-20e471cd078c/lib/karafka/loader.rb:16:in `load'
	from /home/mencio/Pulpit/karafka-boot-report/karafka.rb:7:in `<top (required)>'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bundler/gems/karafka-20e471cd078c/bin/karafka:8:in `require'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bundler/gems/karafka-20e471cd078c/bin/karafka:8:in `<top (required)>'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bin/karafka:23:in `load'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bin/karafka:23:in `<main>'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/mencio/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```
