### ISSUE TITLE
Unable to bundle with karafka in Gemfile on ruby 3.3.4

### ISSUE THREAD

**Issue by eiskrenkov** [karafka/karafka#2172]
I'm unable to run `bundle install` with ruby 3.3.4 having `karafka ~> 2.4` in Gemfile

## Expected behavior

`bundle install` should pass

## Actual behavior

```
karafka-test ) bundle
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Installing karafka-rdkafka 0.16.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/karafka-rdkafka-0.16.0/ext
/Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/bin/ruby -rrubygems /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/rake-13.2.1/exe/rake
RUBYARCHDIR\=/Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/karafka-rdkafka-0.16.0
RUBYLIBDIR\=/Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/karafka-rdkafka-0.16.0
2 retrie(s) left for v2.4.0 (404 Not Found)
1 retrie(s) left for v2.4.0 (404 Not Found)
0 retrie(s) left for v2.4.0 (404 Not Found)
404 Not Found
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - ports/archives/v2.4.0 (Errno::ENOENT)

Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/karafka-rdkafka-0.16.0 for inspection.
Results logged to /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/karafka-rdkafka-0.16.0/gem_make.out

  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/ext/rake_builder.rb:30:in `build'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/source/rubygems.rb:206:in `install'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:132:in `do_install'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/worker.rb:62:in `apply_func'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/worker.rb:54:in `process_queue'
  /Users/eiskrenkov/.local/share/mise/installs/ruby/3.3.4/lib/ruby/3.3.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing karafka-rdkafka (0.16.0), and Bundler cannot continue.

In Gemfile:
  karafka was resolved to 2.4.4, which depends on
    waterdrop was resolved to 2.7.4, which depends on
      karafka-core was resolved to 2.4.3, which depends on
        karafka-rdkafka

```

## Steps to reproduce the problem

```sh
mise use ruby@3.3.4 # or any other way to select ruby 3.3.4
gem install rails
rails new karafka-test
cd karafka-test
bundle add karafka
bundle
```

**Comment by mensfeld** [comment]
I know. All confluent repos are down. I am working on fixing this.

**Comment by eiskrenkov** [comment]
@mensfeld oh sorry for the noise, I assumed this is related to the ruby version

**Comment by mensfeld** [comment]
ref https://github.com/karafka/rdkafka-ruby/issues/465

closing because fixed in most recent versions, slowly backporting.
