### ISSUE TITLE
Karafka::Errors::MissingBootFileError when debugging in VScode with ruby-lsp

### ISSUE THREAD

**Issue by technicalpickles** [karafka/karafka#2300]
## Expected behavior

If you are a VScode user and use ruby-lsp in a Rails app with Karafka, you should be able to debug tests.

https://shopify.github.io/ruby-lsp/#debug-client
https://shopify.github.io/ruby-lsp/#code-lens

## Actual behavior

```
Ruby REPL: You can run any Ruby expression here.
Note that output to the STDOUT/ERR printed on the TERMINAL.
[experimental]
  `,COMMAND` runs `COMMAND` debug command (ex: `,info`).
  `,help` to list all debug commands.

An error occurred while loading ./spec/models/user_spec.rb.
Failure/Error: require_relative '../config/environment'

Karafka::Errors::MissingBootFileError:
  /Users/josh.nichols/workspace/karafka-vscode-lsp-reproduction/.ruby-lsp/karafka.rb
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require_relative'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/models/user_spec.rb:1:in `<top (required)>'
Run options: include {:locations=>{"./spec/models/user_spec.rb"=>[4]}}

All examples were filtered out
```

## Steps to reproduce the problem

[Steps to reproduce](https://github.com/technicalpickles/karafka-debug-rspec-reproduction/issues/1):

- clone this repo
- `bundle install`, `rails db:migrate` and all that
- open in vscode
- add the ruby-lsp extension if you haven't
- open spec/models/user_spec.rb
- use a code lens to "debug"
- see an error in the debug console:

```
Ruby REPL: You can run any Ruby expression here.
Note that output to the STDOUT/ERR printed on the TERMINAL.
[experimental]
  `,COMMAND` runs `COMMAND` debug command (ex: `,info`).
  `,help` to list all debug commands.

An error occurred while loading ./spec/models/user_spec.rb.
Failure/Error: require_relative '../config/environment'

Karafka::Errors::MissingBootFileError:
  /Users/josh.nichols/workspace/karafka-vscode-lsp-reproduction/.ruby-lsp/karafka.rb
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require_relative'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/models/user_spec.rb:1:in `<top (required)>'
Run options: include {:locations=>{"./spec/models/user_spec.rb"=>[4]}}

All examples were filtered out
```

Video:

https://github.com/user-attachments/assets/07b02c64-e25a-46c3-989f-9a6095915993

## Your setup details

```
Karafka version: 2.4.12 + Pro
Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin23]
Rdkafka version: 0.17.3
Consumer groups count: 4
Subscription groups count: 3
Workers count: 5
Application client id: zenpayroll-development-karafka
Boot file: /Users/josh.nichols/workspace/zenpayroll/karafka.rb
Environment: development
License: Commercial
License entity: Gusto
```

**Comment by technicalpickles** [comment]
Here is a very long thread on ruby-dx where we talked about this: https://ruby-dx.slack.com/archives/C050D17S6FP/p1726752422630199

The tl;dr is to use:

```ruby
Bundler.with_unbundled_env { Bundler.default_gemfile }
```

... instead of...

```ruby
ENV['BUNDLE_GEMFILE']
```

for Karafka.root
