### ISSUE TITLE
Default kafka.seed_brokers configuration is created in invalid format

### ISSUE THREAD

**Issue by cebartling** [karafka/karafka#256]
When creating a new project using `bundle exec karafka install`, I get the following generated in the karafka.rb file:

```ruby
...

class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka.seed_brokers = %w( 127.0.0.1:9092 )
    config.client_id = 'example_app'
    config.backend = :inline
    config.batch_fetching = true
  end

  consumer_groups.draw do
    # topic :example do
    #   controller ExampleController
    # end

    # consumer_group :bigger_group do
    #   topic :test do
    #     controller TestController
    #   end
    #
    #   topic :test2 do
    #     controller Test2Controller
    #   end
    # end
  end
end

...
```

When running `bundle exec karafka info`, I get the following error:

```
/Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/waterdrop-1.0.1/lib/water_drop/config.rb:127:in `validate!': {:kafka=>{:seed_brokers=>{0=>["has an invalid format. Expected schema, host and port number. Example: kafka://127.0.0.1:9092 or kafka+ssl://127.0.0.1:9092\n"]}}} (WaterDrop::Errors::InvalidConfiguration)
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/waterdrop-1.0.1/lib/water_drop/config.rb:114:in `block in setup'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/dry-configurable-0.7.0/lib/dry/configurable.rb:70:in `configure'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/waterdrop-1.0.1/lib/water_drop/config.rb:112:in `setup'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/waterdrop-1.0.1/lib/water_drop.rb:23:in `setup'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/karafka-1.1.1/lib/karafka/setup/configurators/water_drop.rb:10:in `setup'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/karafka-1.1.1/lib/karafka/setup/config.rb:147:in `block in setup_components'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/karafka-1.1.1/lib/karafka/setup/config.rb:146:in `each'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/karafka-1.1.1/lib/karafka/setup/config.rb:146:in `setup_components'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/karafka-1.1.1/lib/karafka/app.rb:21:in `boot!'
	from /Users/chris/temp/sentera-karafka-spike/karafka.rb:34:in `<top (required)>'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/karafka-1.1.1/bin/karafka:8:in `require'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/gems/karafka-1.1.1/bin/karafka:8:in `<top (required)>'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/bin/karafka:23:in `load'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/bin/karafka:23:in `<main>'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/bin/ruby_executable_hooks:15:in `eval'
	from /Users/chris/.rvm/gems/ruby-2.4.2@sentera-karafka-spike/bin/ruby_executable_hooks:15:in `<main>'
```

Changing the following line fixes the issue...

```ruby
config.kafka.seed_brokers = %w( kafka://127.0.0.1:9092 )
```

Simple fix, but this really should be fixed in `bundle exec karafka install` generator.

**Comment by mensfeld** [comment]
@cebartling thnak you. This will be fixed today.

**Comment by mensfeld** [comment]
Fixed in https://github.com/karafka/karafka/pull/257
