### ISSUE TITLE
Most recent version from rubygems doesn't require itself pretty well...

### ISSUE THREAD

**Issue by ajgon** [karafka/karafka#303]
```
[~]$ docker run -it ruby bash
root@4aa400787af4:/# ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
root@4aa400787af4:/# gem install karafka
...........................
27 gems installed
root@4aa400787af4:/# irb
irb(main):001:0> require 'karafka'
Traceback (most recent call last):
       11: from /usr/local/bin/irb:11:in `<main>'
       10: from (irb):1
        9: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        8: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        7: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        6: from /usr/local/bundle/gems/karafka-1.1.2/lib/karafka.rb:66:in `<top (required)>'
        5: from /usr/local/bundle/gems/karafka-1.1.2/lib/karafka/loader.rb:26:in `load!'
        4: from /usr/local/bundle/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
        3: from /usr/local/bundle/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
        2: from /usr/local/bundle/gems/require_all-2.0.0/lib/require_all.rb:97:in `block in require_all'
        1: from /usr/local/bundle/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all'
RequireAll::LoadError (Could not require /usr/local/bundle/gems/karafka-1.1.2/lib/karafka/app.rb (uninitialized constant #<Class:Karafka::App>::Status). Please require the necessary files)
irb(main):002:0>
```

**Comment by mensfeld** [comment]
Please lock require all to the last 1.* release. We've made a mistake of not closing this dependencily. It will be fixed with 1.2 release this week (probably today)

**Comment by mensfeld** [comment]
This version should do the trick: https://rubygems.org/gems/require_all/versions/1.5.0

**Comment by ajgon** [comment]
It works, thank you.
