### ISSUE TITLE
ThreadError can't alloc thread

### ISSUE THREAD

**Issue by lewispb** [karafka/karafka#404]
I believe this occurs when our Kafka service, Confluent Cloud rate limits us by timing out connections.

```
ThreadError: can't alloc thread
  from kafka/fetcher.rb:31:in `new'
  from kafka/fetcher.rb:31:in `initialize'
  from kafka/client.rb:311:in `new'
  from kafka/client.rb:311:in `consumer'
  from karafka/connection/client.rb:100:in `kafka_consumer'
  from karafka/connection/client.rb:29:in `fetch_loop'
  from karafka/connection/listener.rb:39:in `fetch_loop'
  from karafka/connection/listener.rb:23:in `call'
  from karafka/fetcher.rb:19:in `block (2 levels) in call'
```

**Comment by mensfeld** [comment]
reproduction for ruby-kafka. If they won't fix it, it will be fixed in Karafka. Worth pointing out in the docs, that it would be good to monitor thread pool as well.

```ruby
begin
 kafka = Kafka.new(
   seed_brokers: brokers,
   client_id: "simple-consumer",
   socket_timeout: 20,
   logger: logger,
 )

   consumer = kafka.consumer(group_id: "firehose")
   consumer.subscribe(topic)


 consumer.each_message(topic: topic) do |message|
   #puts message.value
   #consumer.stop
   raise
 end
rescue => e
 consumer.stop
 p Thread.list.count
 retry
end
```

**Comment by mensfeld** [comment]
Fixed with: https://github.com/zendesk/ruby-kafka/pull/654
