### ISSUE TITLE
uninitialized constant Karafka::BaseConsumer::Forwardable

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#452]
It seems in Ruby 2.6.0 the forwardable needs to be required or it wasn't required directly by us. Anyhow we need to require it.

**Comment by filiptepper** [comment]
```
$ bundle exec karafka install
bundler: failed to load command: karafka (/Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/bin/karafka)
RequireAll::LoadError: Could not require /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/karafka-1.2.9/lib/karafka/base_consumer.rb (uninitialized constant Karafka::BaseConsumer::Forwardable). Please require the necessary files
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:97:in `block in require_all'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/karafka-1.2.9/lib/karafka/loader.rb:25:in `load!'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/karafka-1.2.9/lib/karafka.rb:76:in `<top (required)>'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/karafka-1.2.9/bin/karafka:3:in `require'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/gems/karafka-1.2.9/bin/karafka:3:in `<top (required)>'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/bin/karafka:23:in `load'
  /Users/filiptepper/Code/karafka-consumer/vendor/bundle/ruby/2.5.0/bin/karafka:23:in `<top (required)>'
```
