### ISSUE TITLE
Karafka 1.2.13 CLI fails when consumer class is not defined

### ISSUE THREAD

**Issue by Mehonoshin** [karafka/karafka#513]
Hey guys!

I found a minor issue, that happens when the consumer class referenced at `karafka.rb` file does not exist yet.

For some reason whenever I fire some cli command it fails with such exception:

```
~/p/freya/storage(master ✗) bundle exec karafka info
bundler: failed to load command: karafka (/Users/mexx/.rbenv/versions/2.3.4/bin/karafka)
NameError: uninitialized constant KarafkaApp::ProfileProcessor
  /Users/mexx/p/freya/storage/karafka.rb:32:in `block (3 levels) in <class:KarafkaApp>'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/proxy.rb:21:in `instance_eval'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/proxy.rb:21:in `initialize'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:36:in `new'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:36:in `topic='
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/proxy.rb:27:in `public_send'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/proxy.rb:27:in `method_missing'
  /Users/mexx/p/freya/storage/karafka.rb:31:in `block (2 levels) in <class:KarafkaApp>'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/proxy.rb:21:in `instance_eval'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/proxy.rb:21:in `initialize'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/builder.rb:49:in `new'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/builder.rb:49:in `consumer_group'
  /Users/mexx/p/freya/storage/karafka.rb:30:in `block in <class:KarafkaApp>'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/builder.rb:25:in `instance_eval'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/lib/karafka/routing/builder.rb:25:in `draw'
  /Users/mexx/p/freya/storage/karafka.rb:29:in `<class:KarafkaApp>'
  /Users/mexx/p/freya/storage/karafka.rb:9:in `<top (required)>'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/bin/karafka:8:in `require'
  /Users/mexx/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/karafka-1.2.13/bin/karafka:8:in `<top (required)>'
  /Users/mexx/.rbenv/versions/2.3.4/bin/karafka:23:in `load'
  /Users/mexx/.rbenv/versions/2.3.4/bin/karafka:23:in `<top (required)>'
```

Most probably it tries to evaluate `karafka.rb` on each CLI run, but I believe this error message might be improved and be more user-friendly.

WDYT?

**Comment by mensfeld** [comment]
How would you see it improved? Would would you suggest?

**Comment by Mehonoshin** [comment]
@mensfeld I'm now familiar with internal Karafka implementation, but do we really need to to evaluate the whole routing block for CLI commands?

**Comment by mensfeld** [comment]
Sorry for the delay on that one. Indeed we could improve the message. I will try to take care of that before the 1.3 release. Thank you for reporting.

**Comment by mensfeld** [comment]
Hey,

could you tell me, why the class referenced does not yet exist? I'm trying to come up with a repro for that...

**Comment by mensfeld** [comment]
Closing as stale.
