### ISSUE TITLE
SSL Client Cert Key Error

### ISSUE THREAD

**Issue by arunkarthick** [karafka/karafka#547]
Hello,

My Kafka cluster uses SSL certificate for authentication. Everything on the Kafka side looks good and its working fine. The default Consumer & Producer scripts are working fine with the client ssl certs. Even its working fine when I try it with ruby-kafka from rails console like below

```
kafka = Kafka.new(["kafka01:9093", "kafka02:9093", "kafka03:9093"], client_id: 'devconsole', ssl_ca_cert: File.read("#{Rails.root.to_s}/config/ssl/ca_cert.pem"), ssl_client_cert: File.read("#{Rails.root.to_s}/config/ssl/client_cert.pem"), ssl_client_cert_key: File.read("#{Rails.root.to_s}/config/ssl/client_key.pem"))
```

```
kafka.deliver_message("Hello, World!", topic: 'test')
=> nil
```

I verified it from a different console to receive this message and I am able to receive this message which was sent through 'ruby-kafka'.

So for so good with 'ruby-kafka' based connection & message delivery.

But when I run the "bundle exec karafka s", I get the following error message

```
Karafka::Errors::InvalidConfigurationError: {:ssl_client_cert_key=>["is not a valid private key\n"]}
  /Users/neo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/karafka-1.3.0/lib/karafka/routing/builder.rb:44:in `block in draw'
  /Users/neo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/karafka-1.3.0/lib/karafka/routing/builder.rb:39:in `each'
  /Users/neo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/karafka-1.3.0/lib/karafka/routing/builder.rb:39:in `draw'
  /Users/neo/example_rails_app/karafka.rb:51:in `<class:KarafkaApp>'
  /Users/neo/example_rails_app/karafka.rb:19:in `<top (required)>'
  /Users/neo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
  /Users/neo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:23:in `require'
  /Users/neo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/karafka-1.3.0/bin/karafka:8:in `<top (required)>'
  /Users/neo/.rbenv/versions/2.5.3/bin/karafka:23:in `load'
  /Users/neo/.rbenv/versions/2.5.3/bin/karafka:23:in `<top (required)>'
```

FYI, I tried the same SSL cert/key files for both 'ruby-kafka' based attempt and the usual karafka approach. But its working only with 'ruby-kafka'. Not sure why karafka is complaining about the private key.  This is what I have in my 'karafka.rb' setup block.

```
class KarafkaApp < Karafka::App
  setup do |config|
     config.kafka.seed_brokers = ["kafka01:9093", "kafka02:9093", "kafka03:9093"]
     config.client_id = 'dev_app'
     config.logger = Rails.logger
     config.kafka.start_from_beginning = false
     config.kafka.ssl_ca_cert = File.read("#{Rails.root.to_s}/config/ssl/ca_cert.pem")
     config.kafka.ssl_client_cert = File.read("#{Rails.root.to_s}/config/ssl/client_cert.pem")
     config.kafka.ssl_client_cert_key = File.read("#{Rails.root.to_s}/config/ssl/client_key.pem")
     config.kafka.ssl_verify_hostname = false
  end
  .....
end
```

## My setup details
```
$ [bundle exec] karafka info
Karafka version: 1.3.0
Ruby version: 2.5.3
Ruby-kafka version: 0.7.10
Application client id: dev_app
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /Users/neo/example_rails_app/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://kafka01:9093", "kafka://kafka02:9093", "kafka://kafka03:9093"]
```

I
Any thoughts?

**Comment by arunkarthick** [comment]
I think its because of my DSA private key, because karafka side validation looks for RSA key which throws that "Invalid Private Key" error. So for now, I am going with the below monkey patch (which is working fine)

```
module Karafka
  module Contracts
    class ConsumerGroup < Dry::Validation::Contract
      private

      # @param value [String] potential RSA key value
      # @return [Boolean] is the given string a valid RSA key
      def valid_private_key?(value)
        OpenSSL::PKey::DSA.new(value)
        true
      rescue OpenSSL::PKey::DSAError
        false
      end
    end
  end
end
```

**Comment by mensfeld** [comment]
Hello @arunkarthick. Thank you for such a detailed explanation as well as for the monkey patch. @nijikon will incorporate your solution into Karafka `1.3.1`.

**Comment by arunkarthick** [comment]
Great! Instead of looking for a specific key type, we can try some other validation. May be we can go with something like below

```
begin
  if client_cert_key_password
    cert_key = OpenSSL::PKey.read(client_cert_key, client_cert_key_password)
  else
    cert_key = OpenSSL::PKey.read(client_cert_key)
  end
  true # if private key can be read
rescue OpenSSL::PKey::PKeyError, OpenSSL::PKey::DSAError, OpenSSL::PKey::RSAError
  false # for all other failure case.
end
```

**Comment by mensfeld** [comment]
Yes. We should iterate over all the supported possibilities / cc @nijikon
