### ISSUE TITLE
undefined method `find' for Dry::Configurable::Settings

### ISSUE THREAD

**Issue by anujchandraZ** [karafka/karafka#558]
Unable to run rails application with karafka.

I have the gemfile definition as follows:
```
gem 'karafka', '~> 1.2', '>= 1.2.10'
```

But launching rails console produces the following error:
```
Traceback (most recent call last):
        31: from bin/rails:4:in `<main>'
        30: from bin/rails:4:in `require'
        29: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
        28: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
        27: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
        26: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
        25: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        24: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        23: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/commands/console/console_command.rb:95:in `perform'
        22: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        21: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/command/actions.rb:22:in `require_application!'
        20: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/railties-5.2.3/lib/rails/command/actions.rb:22:in `require'
        19: from /Users/anuj/app/config/application.rb:9:in `<top (required)>'
        18: from /Users/anuj/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
        17: from /Users/anuj/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
        16: from /Users/anuj/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
        15: from /Users/anuj/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
        14: from /Users/anuj/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
        13: from /Users/anuj/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
        12: from /Users/anuj/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
        11: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/karafka-1.2.10/lib/karafka.rb:77:in `<top (required)>'
        10: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/karafka-1.2.10/lib/karafka/loader.rb:25:in `load!'
         9: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/require_all-3.0.0/lib/require_all.rb:96:in `require_all'
         8: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/require_all-3.0.0/lib/require_all.rb:96:in `each'
         7: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/require_all-3.0.0/lib/require_all.rb:98:in `block in require_all'
         6: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/require_all-3.0.0/lib/require_all.rb:208:in `__require'
         5: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/require_all-3.0.0/lib/require_all.rb:208:in `require'
         4: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/karafka-1.2.10/lib/karafka/routing/consumer_group.rb:3:in `<top (required)>'
         3: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/karafka-1.2.10/lib/karafka/routing/consumer_group.rb:4:in `<module:Karafka>'
         2: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/karafka-1.2.10/lib/karafka/routing/consumer_group.rb:8:in `<module:Routing>'
         1: from /Users/anuj/.rvm/gems/ruby-2.5.5/gems/karafka-1.2.10/lib/karafka/routing/consumer_group.rb:40:in `<class:ConsumerGroup>'
/Users/anuj/.rvm/gems/ruby-2.5.5/gems/karafka-1.2.10/lib/karafka/attributes_map.rb:59:in `consumer_group': undefined method `find' for #<Dry::Configurable::Settings:0x00007fb35ae71160> (NoMethodError)
```

There is already an issue opened in #518 which involved upgrading thor but I am looking for solutions which avoid doing that.

**Comment by mensfeld** [comment]
Not gonna be fixed. Sorry :(

**Comment by dduqueti** [comment]
@mensfeld so upgrading `thor` is required? So we can use Karafka `1.2.13`. 

Thanks for your work.
