### ISSUE TITLE
Connection error with heroku kafka addon

### ISSUE THREAD

**Issue by md-farhan-memon** [karafka/karafka#563]
I have been trying to connect `karafka` app to `heroku kafka` addon but I get the following error:

>I, [2019-12-20T17:12:03.425476 #29399]  INFO -- : Fetching cluster metadata from kafka+ssl://ec2-x-x-x-x.compute-1.amazonaws.com:9096
Traceback (most recent call last):
       16: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:52:in 'add_target_topics'
       15: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:98:in 'refresh_metadata!'
       14: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:350:in 'cluster_info'
       13: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:370:in 'fetch_cluster_info'
       12: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:370:in 'each'
       11: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:375:in 'block in fetch_cluster_info'
       10: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/broker.rb:44:in 'fetch_metadata'
        9: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/broker.rb:200:in 'send_request'
        8: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:97:in 'send_request'
        7: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:21:in 'instrument'
        6: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2/lib/active_support/notifications.rb:182:in 'instrument'
        5: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:98:in 'block in send_request'
        4: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:127:in 'open'
        3: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:127:in 'new'
        2: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in 'initialize'
        1: from /home/farhan/.rvm/gems/ruby-2.6.5/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in 'connect_nonblock'
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error))

Following is the configuration in `karafka.rb`

    setup do |config|
      config.kafka.seed_brokers = ENV['KAFKA_URL'].to_s.split(',').map(&:strip)
      if ENV['KAFKA_TRUSTED_CERT']
        tmp_ca_file = ::Tempfile.new('kafka_ca_certs')
        tmp_ca_file.write(ENV.fetch('KAFKA_TRUSTED_CERT'))
        tmp_ca_file.close
        config.kafka.ssl_ca_cert_file_path = tmp_ca_file.path
      end
      if ENV['KAFKA_CLIENT_CERT'] && ENV['KAFKA_CLIENT_CERT_KEY']
        config.kafka.ssl_client_cert = ENV['KAFKA_CLIENT_CERT']
        config.kafka.ssl_client_cert_key = ENV['KAFKA_CLIENT_CERT_KEY']
      end
      config.client_id = 'async_processor'
    end

**What I tried**

 - `OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE`

But then I get different error:

> ERROR -- : Failed to assign partitions to 1 messages in TutorialTopic

**Maybe helpful point**
Since it is a shared cluster, I have a config in heroku name `KAFKA_PREFIX` not sure what to do with it, tried appending it to the topic but in vain.

What am I missing?

Info:
```
ruby '2.6.5'
karafka '1.3.1'
```

**Comment by mensfeld** [comment]
Did you look here?

https://github.com/karafka/karafka/wiki/Deployment#heroku

**Comment by md-farhan-memon** [comment]
yes @mensfeld, above code snippet is from there itself.

**Comment by mensfeld** [comment]
@md-farhan-memon I don't know how Heroku works (I had some unpleasantness trying to establish a relationship with them) but since you have `KAFKA_PREFIX` it looks like you will have to (based on https://devcenter.heroku.com/articles/multi-tenant-kafka-on-heroku) use a custom mapper that will remap the topic name to one with the prefix: https://github.com/karafka/karafka/wiki/Consumer-and-topic-mappers

**Comment by md-farhan-memon** [comment]
this [issue](https://github.com/zendesk/ruby-kafka/issues/778) at `ruby-kafka` mentions to set `ssl_verify_hostname` config as false, did that but it is giving the second error from above.

> ERROR -- : Failed to assign partitions to 1 messages in TutorialTopic

**Comment by mensfeld** [comment]
I know. Did you establish a  proper topic mapper?

**Comment by md-farhan-memon** [comment]
> I know. Did you establish a proper topic mapper? It looks like you can establish connection, you're just trying to reach a topic that is not under your ownership :)

Yep, I didn't look at the code but it seems `ssl_verify_hostname` config is doing similar to `OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE` internally that's why ssl error is resolved.

Isn't that a security risk?

Let me try topic mappers and I'll update here. Thanks..

**Comment by mensfeld** [comment]
> Isn't that a security risk?

big topic. Is and isn't. Different discussion. We're moving away from ruby-kafka for many reasons and that's one of them.

> Let me try topic mappers and I'll update here. Thanks.

I'm almost 100% sure it will help. If all works, please close the issue :) otherwise ofc ping me and we will try to work things out!

**Comment by md-farhan-memon** [comment]
@mensfeld mapper is not helping. I even tried manually adding the prefix to the topic, but same error.. :(

**Comment by mensfeld** [comment]
@md-farhan-memon it's impossible. If you would add the mapper, the error would contain a different topic name.

**Comment by md-farhan-memon** [comment]
> We're moving away from ruby-kafka for many reasons and that's one of them.

Really? What is the timeline for that? I am trying to use karafka without rails as independent framework, what do you suggest?

> @md-farhan-memon it's impossible. If you would add the mapper, the error would contain a different topic name.

ofcourse, the topic is different but error is same

`Failed to assign partitions to 1 messages in Prefix.Topic`

**Comment by mensfeld** [comment]
Hmmm there's definitely something wrong with the settings @md-farhan-memon. Would you mind creating a reproduction repository?

**Comment by mensfeld** [comment]
@md-farhan-memon did you manage to fix it?

**Comment by mensfeld** [comment]
Closing due to lack of activity.
