### ISSUE TITLE
ThreadError: can't be called from trap context

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#578]
When Karafka runs and we press CTRL + C with patched ruby-kafka, following error is being raised:

```ruby
bundler: failed to load command: karafka (/home/mencio/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bin/karafka)
ThreadError: can't be called from trap context
  concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:18:in `synchronize'
  concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:18:in `[]='
  dry-configurable-0.11.3/lib/dry/configurable/config.rb:118:in `block in resolve'
  concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/map.rb:172:in `fetch'
  dry-configurable-0.11.3/lib/dry/configurable/config.rb:118:in `resolve'
  dry-configurable-0.11.3/lib/dry/configurable/config.rb:103:in `method_missing'
  karafka-1.3.4/lib/karafka/server.rb:63:in `stop_supervised'
  karafka-1.3.4/lib/karafka/server.rb:27:in `block in run'
  karafka-1.3.4/lib/karafka/process.rb:46:in `each'
  karafka-1.3.4/lib/karafka/process.rb:46:in `block in trap_signal'
  karafka-1.3.4/lib/karafka/fetcher.rb:24:in `join'
  karafka-1.3.4/lib/karafka/fetcher.rb:24:in `each'
  karafka-1.3.4/lib/karafka/fetcher.rb:24:in `call'
  karafka-1.3.4/lib/karafka/server.rb:53:in `run_supervised'
  karafka-1.3.4/lib/karafka/server.rb:30:in `run'
  karafka-1.3.4/lib/karafka/cli/server.rb:42:in `call'
  karafka-1.3.4/lib/karafka/cli/base.rb:62:in `block in bind_to'
  thor-1.0.1/lib/thor/command.rb:27:in `run'
  thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  thor-1.0.1/lib/thor.rb:392:in `dispatch'
  thor-1.0.1/lib/thor/base.rb:485:in `start'
  karafka-1.3.4/bin/karafka:19:in `<top (required)>'
  /home/mencio/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bin/karafka:23:in `load'
```

**Comment by mensfeld** [comment]
It's actually a dry-configurable error but will patch it.

**Comment by mensfeld** [comment]
ref: https://github.com/dry-rb/dry-configurable/issues/93
