### ISSUE TITLE
Usage with Hanami

### ISSUE THREAD

**Issue by Samsinite** [karafka/karafka#612]
Hi! Trying to install karafka into a new hanami project, and when the gem is installed I instantly get an error:

```
NoMethodError: undefined method `settings' for #<Dry::Configurable::Settings:0x00007ff8405f1668>
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/attributes_map.rb:60:in `consumer_group'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:40:in `<class:ConsumerGroup>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:8:in `<module:Routing>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:4:in `<module:Karafka>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:3:in `<top (required)>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:208:in `require'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:208:in `__require'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:98:in `block in require_all'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:96:in `each'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:96:in `require_all'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/loader.rb:25:in `load!'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka.rb:77:in `<top (required)>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/bin/karafka:3:in `require'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/bin/karafka:3:in `<top (required)>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/bin/karafka:23:in `load'
  /Users/samueljclopton/.rbenv/versions/2.5.7/bin/karafka:23:in `<top (required)>'
```

Any suggestions on how to make this work with a default Hanami setup would be much appreciated. It appears that there is a conflicting dependency, as removing every gem other than karafka does make the karafka cli work, I'm guessing it is due to one of the dry-rb dependencies as both Hanami and Karafka use libraries from the dry-rb ecosystem. Any help would be much appreciated, thanks!

--------

## Expected behavior

The application boots and both `bundle exec karafka install` and `bundle exec karafka server` works.

## Actual behavior

Application errors with the above error when booting the Hanami server, or running any part of the karafka CLI.

## Steps to reproduce the problem

Create a new Hanami application, install the karafka gem, run any of the karafka cli commands or try to boot the Hanami server.

## Your setup details

Can't run `bundle exec karafka info`:
```
$ [bundle exec] karafka info
NoMethodError: undefined method `settings' for #<Dry::Configurable::Settings:0x00007fcb80c0c6c0>
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/attributes_map.rb:60:in `consumer_group'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:40:in `<class:ConsumerGroup>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:8:in `<module:Routing>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:4:in `<module:Karafka>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/routing/consumer_group.rb:3:in `<top (required)>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:208:in `require'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:208:in `__require'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:98:in `block in require_all'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:96:in `each'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/require_all-3.0.0/lib/require_all.rb:96:in `require_all'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka/loader.rb:25:in `load!'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/lib/karafka.rb:77:in `<top (required)>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/bin/karafka:3:in `require'
  /Users/samueljclopton/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/karafka-1.2.13/bin/karafka:3:in `<top (required)>'
  /Users/samueljclopton/.rbenv/versions/2.5.7/bin/karafka:23:in `load'
  /Users/samueljclopton/.rbenv/versions/2.5.7/bin/karafka:23:in `<top (required)>'
```
but, if I remove all other gems, I get:

```
Ruby version: 2.5.7
Ruby-kafka version: 1.2.0
Application client id: example_app
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /Users/samueljclopton/workspace/conify_backend/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://127.0.0.1:9092"]
```

**Comment by Samsinite** [comment]
If this helps, when I remove the karafka dependency, here are the changes in the dry-rb suite of gems:
```
Using dry-initializer 1.4.1 (was 3.0.3)
Using dry-logic 0.4.2 (was 1.0.7)
Using dry-types 0.11.1 (was 1.4.0)
Using dry-validation 0.11.0 (was 1.5.6)
```

Should karafka's gemspec pin these gems to the supported versions?

**Comment by Samsinite** [comment]
Found it, appeared to be an issue with dry-initializer, recommend pinning the version of this gem to its supported versions.

**Comment by Samsinite** [comment]
Actually, it appears that karafka does pin it to `~1.2`, any ideas why the bundle update didn't fail?

**Comment by mensfeld** [comment]
@Samsinite o wow :) That was quick! If there's anything I can fix in the gemspec, just ping me!
