### ISSUE TITLE
undefined method `delegate' for Scenic::Adapters::Postgres::Indexes:Class

### ISSUE THREAD

**Issue by jedrekdomanski** [karafka/karafka#709]
*Be clear, concise and precise in your description of the problem.
Open an issue with a descriptive title and a summary in grammatically correct,
complete sentences.*

*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable Karafka and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*Before filing the ticket you should replace all text above the horizontal
rule with your own words.*

--------

## Expected behavior

Karafka commands work

## Actual behavior
Any karafka command raise an error:
```
bundle exec karafka server
Traceback (most recent call last):
	25: from /home/jedrek/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	24: from /home/jedrek/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	23: from /home/jedrek/.rvm/gems/ruby-2.6.5/bin/karafka:23:in `<main>'
	22: from /home/jedrek/.rvm/gems/ruby-2.6.5/bin/karafka:23:in `load'
	21: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/karafka-1.4.7/bin/karafka:8:in `<top (required)>'
	20: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	19: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	18: from /home/jedrek/workspace/ironin/lease_management_system/karafka.rb:9:in `<top (required)>'
	17: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/bundler-2.2.24/lib/bundler.rb:174:in `require'
	16: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/bundler-2.2.24/lib/bundler/runtime.rb:48:in `require'
	15: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/bundler-2.2.24/lib/bundler/runtime.rb:48:in `each'
	14: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/bundler-2.2.24/lib/bundler/runtime.rb:59:in `block in require'
	13: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/bundler-2.2.24/lib/bundler/runtime.rb:59:in `each'
	12: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/bundler-2.2.24/lib/bundler/runtime.rb:64:in `block (2 levels) in require'
	11: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	10: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 9: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic.rb:2:in `<top (required)>'
	 8: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 7: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 6: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic/adapters/postgres.rb:4:in `<top (required)>'
	 5: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic/adapters/postgres.rb:4:in `require_relative'
	 4: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic/adapters/postgres/indexes.rb:1:in `<top (required)>'
	 3: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic/adapters/postgres/indexes.rb:2:in `<module:Scenic>'
	 2: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic/adapters/postgres/indexes.rb:3:in `<module:Adapters>'
	 1: from /home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic/adapters/postgres/indexes.rb:7:in `<class:Postgres>'
/home/jedrek/.rvm/gems/ruby-2.6.5/gems/scenic-1.5.4/lib/scenic/adapters/postgres/indexes.rb:23:in `<class:Indexes>': undefined method `delegate' for Scenic::Adapters::Postgres::Indexes:Class (NoMethodError)
Did you mean?  DelegateClass
```
This happens with any `karafka` command

## Steps to reproduce the problem
Run any karafka command, i.e bundle exec karafka server or bundle exec karafka info

## Your setup details
rails 6.1.3.2
ruby 2.6.5
kafka_2.13-2.8.0 
karafka-1.4.7

Here's an example:

```
$ [bundle exec] karafka info
Karafka version: 1.3.0
Ruby version: 2.6.3
Ruby-kafka version: 0.7.9
Application client id: karafka-local
Backend: inline
Batch fetching: true
Batch consuming: true
Boot file: /app/karafka/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://kafka:9092"]
```

**Comment by mensfeld** [comment]
Does it happen locally as well? Hence outside of Heroku?

**Comment by jedrekdomanski** [comment]
Yes, locally. I have a Kafka server running locally and I am trying to integrate `karafka` with my Rails app and I am having no luck running it.

**Comment by mensfeld** [comment]
@jedrekdomanski that has nothing to do with Karafka actually and all with your app loading process ;) drop me an email and we can jump on a quick zoom call to fix it. Will be much faster than writing (maciej@mensfeld.pl)

**Comment by jedrekdomanski** [comment]
It looks like I can't read and didn't go over the section for configuring Rails applications. All good :) Thanks @mensfeld :+1: Best support ever!
