### ISSUE TITLE
Freshly installed Karafka not booting up

### ISSUE THREAD

**Issue by Loschcode** [karafka/karafka#725]
I've got this in `karafka.rb`

```ruby
# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'development'
ENV['KARAFKA_ENV'] = ENV['RAILS_ENV']
require ::File.expand_path('../config/environment', __FILE__)
Rails.application.eager_load!

# This lines will make Karafka print to stdout like puma or unicorn
if Rails.env.development?
  Rails.logger.extend(
    ActiveSupport::Logger.broadcast(
      ActiveSupport::Logger.new($stdout)
    )
  )
end

class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka.seed_brokers = %w[kafka://localhost:9092]
    config.client_id = ENV['SERVICE_NAME'] || 'unknown'
    config.logger = Rails.logger
  end

  # Comment out this part if you are not using instrumentation and/or you are not
  # interested in logging events for certain environments. Since instrumentation
  # notifications add extra boilerplate, if you want to achieve max performance,
  # listen to only what you really need for given environment.
  Karafka.monitor.subscribe(WaterDrop::Instrumentation::StdoutListener.new)
  Karafka.monitor.subscribe(Karafka::Instrumentation::StdoutListener.new)
  Karafka.monitor.subscribe(Karafka::Instrumentation::ProctitleListener.new)

  # Uncomment that in order to achieve code reload in development mode
  # Be aware, that this might have some side-effects. Please refer to the wiki
  # for more details on benefits and downsides of the code reload in the
  # development mode
  #
  # Karafka.monitor.subscribe(
  #   Karafka::CodeReloader.new(
  #     *Rails.application.reloaders
  #   )
  # )

  consumer_groups.draw do
    topic "events.registrations" do
      consumer EventsRegistrationsConsumer
    end
  end
end

Karafka.monitor.subscribe('app.initialized') do
  # Put here all the things you want to do after the Karafka framework
  # initialization
end

KarafkaApp.boot!
```

--------

## Expected behavior

It should boot up without problem

## Actual behavior

It crashes.

```
Traceback (most recent call last):
	8: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	7: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:24:in `eval'
	6: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/vendor/bundle/ruby/2.7.0/bin/karafka:23:in `<main>'
	5: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/vendor/bundle/ruby/2.7.0/bin/karafka:23:in `load'
	4: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/vendor/bundle/ruby/2.7.0/gems/karafka-1.4.9/bin/karafka:8:in `<top (required)>'
	3: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	2: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	1: from /Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/karafka.rb:17:in `<top (required)>'
/Users/loschcode/Desktop/work/projects/livestorm/livestorm-app/packages/backend/karafka.rb:28:in `<class:KarafkaApp>': undefined method `subscribe' for nil:NilClass (NoMethodError)
```

## Steps to reproduce the problem

- Install Karafka
- Paste this configuration
- It crashes

## Your setup details

I can't execute `karafka info` as it crashes on start-up. Per my `Gemfile.lock` I use `karafka (1.4.9)` and Ruby 2.7.1 with Rails 6.0

**Comment by mensfeld** [comment]
Would you mind sharing your Gemfile?

**Comment by Loschcode** [comment]
I've tried it out on a lighter app and it worked, so I believe it's related to this app specifically, which's the biggest for us.

```ruby
source "https://rubygems.org"

ruby "2.7.1"

# Main
gem "rails", "6.0.3"
gem "net-ssh", ">= 4.0.0"
gem "net-sftp"
gem "faraday"
gem "rack"

gem "karafka"

# Engines
gem "engines-core", path: "../engines/core"

# Typing
gem "rbs", require: false
gem "typeprof", require: false
gem "steep", require: false

# Jobs
# gem 'rack-protection'
gem "sinatra", require: false

gem "sidekiq"

source "https://enterprise.contribsys.com/" do
  gem "sidekiq-pro"
  gem "sidekiq-ent"
end

gem "sidekiq-unique-jobs", "~>6.0"
gem "sidekiq-batch"
gem "sidekiq_queue_metrics"
gem "sidekiq-status"

# Seeds, tests (needed in all env)
gem "factory_bot"
gem "database_cleaner"
gem "faker"

# Server websocket
gem "puma", "~> 4.3.6"
# Feature flipping
gem "flipper"
gem "flipper-ui"
gem "flipper-redis"

# Opentok
gem "opentok"

# Dial-In
gem "nexmo"

# Store
gem "redis", "~> 4.1"
gem "pg"

# Utilitaries
gem "groupdate"
gem "rubyzip", "~> 1.3"
gem "axlsx", git: "https://github.com/randym/axlsx"
gem "spreadsheet_architect", "4.0.0"
gem "hashie"
gem "enumerize"
gem "scenic"
gem "discard"
gem "marginalia", require: false
gem "active_record_extended"
gem "namecase", git: "https://github.com/livestorm/namecase"
gem "excon"

# Assets
gem "uglifier"
gem "coffee-rails"
gem "sass-rails"
gem "sassc", "2.4.0"

# i18n API
gem "http_accept_language"

# Date & time
gem "icalendar" # ICS generator
gem "tzinfo", "1.2.7"

# API
gem "jbuilder"
gem "jsonapi-serializer"

# Auth
gem "omniauth"
gem "omniauth-hubspot-full"
gem "saml2"
gem "nokogiri-xmlsec-instructure", "0.10.1"
gem "devise"
gem "jwt", "~> 2.1"

# Mail
gem "sendgrid-ruby"
gem "postmark-rails"
gem "inky-rb", require: "inky"
gem "premailer-rails"
gem "nokogiri"
gem "foundation_emails"
gem "liquid"
gem "mjml-rails"

# Config ENV variable
gem "figaro"

# Pagination
gem "kaminari"

# Dry-rb
gem "dry-monads"

# Active Admin
gem "activeadmin"
gem "activeadmin_addons", git: "https://github.com/platanus/activeadmin_addons"
gem "active_admin_theme"

# Image treatment & storage
gem "rmagick"
gem "mini_magick"
gem "carrierwave"
gem "carrierwave-aws"
# gem 'carrierwave-video'
# gem 'carrierwave-video-thumbnailer'
gem "aws-sdk-mediaconvert"

# Integration
gem "analytics-ruby" # Segment.io
gem "zapier_ruby"
gem "slack-notifier"
gem "pipedrive.rb", git: "https://github.com/amoniacou/pipedrive.rb"
gem "hubspot-api-client"
gem "omniauth-salesforce", "~> 1.0", ">= 1.0.5"
gem "restforce", "~> 5.0.5"
gem "savon", "~> 2.12.0"
gem "mrkt" # marketo

# gem 'markety'
gem "kickbox" # Email verification
gem "customerio"

gem "rack-cors", require: "rack/cors"

# Bug catcher
gem "sentry-ruby"
gem "sentry-rails"
gem "sentry-sidekiq"

# UserAgent parser
gem "browser"

# IP Geocoding
gem "geocoder"

# Logs clean
gem "ddtrace"
gem "dogstatsd-ruby"
gem "lograge", git: "https://github.com/jefflub/lograge.git"

# ChargeBee
gem "chargebee", "~>2"

gem "asset_sync"
gem "fog-aws"

# Profiling
gem "active_model_serializers"
gem "paper_trail"
gem "strong_migrations"
gem "bootsnap", require: false

gem "wisper"

# DevOps
# Notify Slack after running commands like db:migrate on envs
gem "slack-ruby-client"

# Public API
gem "jsonapi-utils", "~> 0.7.2" # For Rails 5
gem "jsonapi-resources", "0.9.11" # Fix version for MonkeyPatch
gem "rswag-api", "~> 2.3", ">= 2.3.1"
gem "rswag-ui", "~> 2.3", ">= 2.3.1"
gem "rswag", "~> 2.3", ">= 2.3.1"
# Need this here because of
# https://github.com/rswag/rswag/tree/2.2.0#enable-generation-examples-from-responses
gem "rswag-specs", "~> 2.3", ">= 2.3.1"
gem "jsonapi-swagger"
gem "doorkeeper"

# Other
gem "oj"

# Security
gem "rack-attack"

# Scaling read replicas
gem "distribute_reads", git: "https://github.com/livestorm/distribute_reads.git", branch: "named_connections"
gem "makara"

# CloudWatch Metrics
gem "aws-sdk-cloudwatch"

group :development, :staging, :production do
  # Server websocket
  # Do not include in test groupe because of AnyCable compatibility issue
  gem "anycable-rails", "~> 1.0"
end

group :development do
  gem "web-console"
  gem "better_errors"
  gem "spring"
  gem "listen"
  gem "rails-erd", require: false
  gem "brakeman", require: false
  gem "guard-rspec", require: false
  gem "derailed_benchmarks"
  gem "tty-prompt", require: false
  gem "sprockets", "~> 3.7.2"
end

group :staging, :development do
  gem "meta_request"
end

group :development, :test, :staging do
  gem "rspec-rails"
  gem "rspec-activemodel-mocks"
  gem "timecop"
end

group :development, :test do
  gem "active_record_query_trace"
end

group :development, :test do
  gem "pry-rails"
  gem "bullet"

  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-shopify", require: false
  gem "pry-rescue"
  gem "pry-stack_explorer"
  gem "browserstack-local"
  gem "ruby_jard"
end

group :test do
  gem "capybara"
  gem "capybara-screenshot"
  gem "webdrivers"
  gem "rspec_junit_formatter"
  gem "shoulda-matchers"
  gem "shoulda-callback-matchers", "~> 1.1.1"
  gem "simplecov-cobertura"
  gem "rails-controller-testing"
  gem "webmock"
  gem "rspec-retry"
  gem "rspec-json_expectations"
  gem "rubocop-rspec"
  gem "rspec-sidekiq"
  gem "crystalball"
  gem "rspec-benchmark"
  gem "rack-test", require: "rack/test"
  gem "jsonapi-resources-matchers"
  gem "allure-rspec", "~> 2"
  gem "vcr"
end

group :production do
  gem "passenger"
end
```

**Comment by mensfeld** [comment]
> I've tried it out on a lighter app and it worked, so I believe it's related to this app specifically, which's the biggest for us.

Yeah it also works in the demo app. It may be related to a dry-deps version problem. Would you mind sharing the lockfile as well please?

**Comment by mensfeld** [comment]
as a bypass you could try:

```ruby
  setup do |config|
    config.kafka.seed_brokers = %w[kafka://localhost:9092]
    config.client_id = ENV['SERVICE_NAME'] || 'unknown'
    config.logger = Rails.logger
    config.monitor = ::Karafka::Instrumentation::Monitor.new
  end
```

though this issue is really... interesting.

We can jump on a quick zoom call tomorrow to figure that out. p2p debug is much better than guessing. If not, I can fix it (if a bug) if you provide me with a repro

**Comment by Loschcode** [comment]
Yes we should definitely do that, I've sent you an invite on your email.

**Comment by mensfeld** [comment]
Closing this one as per our email exchange problem was solved and it was app specific (not karafka related directly).
