### ISSUE TITLE
Karafka fails to boot with TypeError after deleting a consumer from the group

### ISSUE THREAD

**Issue by BatuhanW** [karafka/karafka#727]
We have an unused topic (let's call it `topic-b`) and when we try to delete topic's consumer from it's group, we are getting an error *during deployment*.  Karafka server fails to start and we didn't delete this topic (yet), so it's still there.

If that helps, in the same PR, we also deleted related `.._consumer.rb` file.

`Fetcher crash due to an error: no implicit conversion of nil into Integer`

Related part of `karafka.rb` looks like this:
```
....

consumer_group :some_group do
  # ...other topics and consumers

  topic 'topic-a' do
    consumer ::SomeConsumer
  end

  # This part is deleted
  topic 'topic-b' do
    consumer ::DeletedConsumer
  end
  # This part is deleted
end

....
```

## Expected behavior

Karafka should be able to boot without problems.

## Actual behavior

Karafka failed to boot and deployment is failed.

## Steps to reproduce the problem

- Create a consumer group
- Add a consumer to the topic
- Deploy
- ~Delete recently added consumer~ Edit: remove the `topic "xxx" do` block from the group.
- Deploy

## Your setup details

Logs taken from production.

```
$ [bundle exec] karafka info

I, [2021-11-11T18:26:13.044582 #1]  INFO -- : Initializing Karafka server 1
I, [2021-11-11T18:26:13.065231 #1]  INFO -- : Karafka version: 1.3.7
Ruby version: 2.6.3
Ruby-kafka version: 1.2.0
Application client id: [APP NAME]
Backend: inline
Batch fetching: false
Batch consuming: false
Boot file: /home/[APP NAME]/app/karafka.rb
Environment: development
```

## Stacktrace

I redacted topic names. `UNUSED_TOPIC` is the one we are trying to delete it's consumer.

```
.....
{}
:] There are no partitions to fetch from, sleeping for 1s
I, [2021-11-11T18:26:18.310683 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 3]/0 to offset 1287241
I, [2021-11-11T18:26:18.310793 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 3]/2 to offset 1295975
I, [2021-11-11T18:26:18.310864 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 5]/1 to offset 297127
I, [2021-11-11T18:26:18.310933 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 8][REDACTED SUFFIX 1]/0 to offset 2186701
I, [2021-11-11T18:26:18.311002 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 8][REDACTED SUFFIX 1]/2 to offset 2177490
I, [2021-11-11T18:26:18.311068 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 11]/5 to offset 1301
I, [2021-11-11T18:26:18.311135 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 11]/2 to offset 1299
I, [2021-11-11T18:26:18.311200 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 11]/1 to offset 1291
I, [2021-11-11T18:26:18.311267 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 11]/6 to offset 1489
I, [2021-11-11T18:26:18.311332 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 11]/3 to offset 1357
I, [2021-11-11T18:26:18.311397 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 12]/5 to offset 1266
I, [2021-11-11T18:26:18.311464 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 12]/2 to offset 1232
I, [2021-11-11T18:26:18.311531 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 12]/1 to offset 1242
I, [2021-11-11T18:26:18.311595 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 12]/6 to offset 1186
I, [2021-11-11T18:26:18.311661 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 12]/3 to offset 1246
I, [2021-11-11T18:26:18.311725 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 13]/1 to offset 3634
I, [2021-11-11T18:26:18.311791 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 14]/0 to offset 1450
I, [2021-11-11T18:26:18.311856 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 14]/2 to offset 1509
I, [2021-11-11T18:26:18.311921 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [TOPIC 15]/1 to offset 1084
I, [2021-11-11T18:26:18.311988 #1]  INFO -- : [[[APP NAME][GROUP 3][REDACTED SUFFIX 1]] {[TOPIC 3]: 0, 2; [TOPIC 5]: 1; [TOPIC 8][REDACTED SUFFIX 1]: 0, 2; [TOPIC 11]: 5, 2, 1, 6, 3; [TOPIC 12]: 5, 2, 1, 6, 3; [TOPIC 13]: 1; [TOPIC 14]: 0, 2; [TOPIC 15]: 1; [UNUSED TOPIC]: 0}:] Seeking [UNUSED TOPIC]/0 to offset 8
#<Thread:0x00005609e92e2a90@/usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:57 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:57:in `pack': no implicit conversion of nil into Integer (TypeError)
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:57:in `write_int32'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `each'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `write_array'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `each'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `write_array'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:55:in `encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/request_message.rb:22:in `encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:178:in `encode_with'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:168:in `write_request'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:107:in `block in send_request'
	from /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:21:in `block in instrument'
	from /usr/local/bundle/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:35:in `instrument'
	from /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:20:in `instrument'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/instrumenter.rb:21:in `instrument'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:100:in `send_request'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/broker.rb:200:in `send_request'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/broker.rb:54:in `fetch_messages'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:81:in `block in execute'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `each'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `flat_map'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `execute'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:204:in `fetch_batches'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:160:in `step'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:114:in `loop'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:59:in `block in start'
bundler: failed to load command: karafka (/usr/local/bundle/bin/karafka)
TypeError: no implicit conversion of nil into Integer
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:57:in `pack'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:57:in `write_int32'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `each'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `write_array'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `each'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `write_array'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:55:in `encode'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/request_message.rb:22:in `encode'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:178:in `encode_with'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:168:in `write_request'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:107:in `block in send_request'
  /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:21:in `block in instrument'
  /usr/local/bundle/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:35:in `instrument'
  /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:20:in `instrument'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/instrumenter.rb:21:in `instrument'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:100:in `send_request'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/broker.rb:200:in `send_request'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/broker.rb:54:in `fetch_messages'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:81:in `block in execute'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `each'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `flat_map'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `execute'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:204:in `fetch_batches'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:160:in `step'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:114:in `loop'
  /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:59:in `block in start'
#<Thread:0x00005609e7664c88@/usr/local/bundle/gems/karafka-1.3.7/lib/karafka/fetcher.rb:18 run> terminated with exception (report_on_exception is true):


/usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:57:in `pack': no implicit conversion of nil into Integer (TypeError)
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:57:in `write_int32'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `each'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `write_array'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `each'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:82:in `write_array'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/fetch_request.rb:55:in `encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/request_message.rb:22:in `encode'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/protocol/encoder.rb:178:in `encode_with'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:168:in `write_request'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:107:in `block in send_request'
	from /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:21:in `block in instrument'
	from /usr/local/bundle/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:35:in `instrument'
	from /usr/local/bundle/gems/appsignal-2.10.12/lib/appsignal/hooks/active_support_notifications.rb:20:in `instrument'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/instrumenter.rb:21:in `instrument'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/connection.rb:100:in `send_request'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/broker.rb:200:in `send_request'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/broker.rb:54:in `fetch_messages'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:81:in `block in execute'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `each'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `flat_map'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetch_operation.rb:71:in `execute'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:204:in `fetch_batches'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:160:in `step'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:114:in `loop'
	from /usr/local/bundle/gems/ruby-kafka-1.2.0/lib/kafka/fetcher.rb:59:in `block in start'

       .........

F, [2021-11-11T18:26:20.372638 #1] FATAL -- : Fetcher crash due to an error: no implicit conversion of nil into Integer
I, [2021-11-11T18:26:20.375857 #1]  INFO -- : Stopping Karafka server 1

  ......

E, [2021-11-11T18:26:21.185568 #1] ERROR -- : Listener fetch loop error: no implicit conversion of nil into Integer


```

Note: I'm going to add more detailed logs after getting approval from the security.

**Comment by mensfeld** [comment]
By saying `Delete recently added consumer` you mean "remove the proper routing reference, so this topic data is not being fetched by the consumer and then re-deploy", right?

**Comment by BatuhanW** [comment]
>By saying Delete recently added consumer you mean "remove the proper routing reference, so this topic data is not being fetched by the consumer and then re-deploy", right?

Sorry if it's not clear enough. And yeah, exactly, I just removed the `topic 'xxxx' do` block.

**Comment by mensfeld** [comment]
@BatuhanW yeah it was not clear at all. At first, I thought you're kicking the process out from Kafka point of view but now I get it. Basically, you remove one of the topics from the group and it still picks up remnants of it after the deploy. Let me look into that...

**Comment by mensfeld** [comment]
@BatuhanW if you took logs from production than what is that?

```
Environment: development
```

**Comment by mensfeld** [comment]
Also please upgrade `ruby-kafka` to 1.4.0. There has been several improvements around managing transactions. Same applies to Karafka. There's `1.4.10` already. The version you are using is almost 1.5 year old.

**Comment by BatuhanW** [comment]
>@BatuhanW if you took logs from production than what is that?

I was gonna ask question about that too but thought that would belong to another issue/question. Our karafka.rb file generated from [the template here](https://github.com/karafka/karafka/blob/master/lib/karafka/templates/karafka.rb.erb#L4-L16). 

What we have still exactly the same as in the template. And we already have `RAILS_ENV` assigned on production servers. Gonna investigate the that one.

```
# frozen_string_literal: true

# Ruby on Rails setup
ENV['RAILS_ENV'] ||= 'development'
ENV['KARAFKA_ENV'] = ENV['RAILS_ENV']
require ::File.expand_path('../config/environment', __FILE__)
Rails.application.eager_load!

# This lines will make Karafka print to stdout like puma or unicorn
if Rails.env.development?
  Rails.logger.extend(
    ActiveSupport::Logger.broadcast(ActiveSupport::Logger.new($stdout))
  )
end
```

By the way is there anything we need to be careful about fixing ENV and setting it to production from development?

**Comment by mensfeld** [comment]
If you would have `RAILS_ENV` in production it would pick it up. I don't recall anything in particular except code reloading that would be affected and since you removed majority of `karafka.rb` hard to say what could be affected by that.

**Comment by mensfeld** [comment]
@BatuhanW any update here?

**Comment by BatuhanW** [comment]
> @BatuhanW any update here?

For now,we put topic route block back with an empty consumer as a workaround. We will take a look at upgrading the version and environment issue after Black Friday.

**Comment by mensfeld** [comment]
Aside from this in 1.4, I added an integration test to see if that case works well in 2.0: https://github.com/karafka/karafka/pull/738/files#diff-0c1e481fd1b2b2c256da0319396b41241c243eeb3e2e47015a7c5f1c243dcc62

**Comment by mensfeld** [comment]
Closing due to lack of activity. I also was not able to reproduce. Feel free to reopen with a repro repo.
